spring:
  datasource:
    url: ${JAWSDB_URL:jdbc:mysql://jlm5jccg4ynuyp4x:gu0ib3sydpeg8ixm@c8u4r7fp8i8qaniw.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/wmsfvs941zw6czk7}
  redis:
    host: eu1-noted-filly-38617.upstash.io
    port: 38617
    password: 6d2057be92c343a2a6889e8e7f1b9a67
    timeout: 3000ms
    ssl: true

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.macro.mall: info