server:
  port: 8077
  tomcat:
    max-http-form-post-size: 50MB

aws:
  access-key: ${BUCKETEER_AWS_ACCESS_KEY_ID:AKIARVGPJVYVDK4AKL5V}
  secret-key: ${BUCKETEER_AWS_SECRET_ACCESS_KEY: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}
  region: ${BUCKETEER_AWS_REGION:eu-west-1}
  bucket-name: ${BUCKETEER_BUCKET_NAME:bucketeer-1a682029-f982-4755-8e3c-663c7658c9b8}
  public-url: ${BUCKETEER_PUBLIC_URL:https://bucketeer-1a682029-f982-4755-8e3c-663c7658c9b8.s3.amazonaws.com/}

spring:
  application:
    name: DoS
  profiles:
    active: dev
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/**
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+1
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  web:
    resources:
      static-locations:
        - classpath:/static/
        - classpath:/public/
        - classpath:/resources/
        - classpath:/META-INF/resources/
        - classpath:/META-INF/resources/webjars/
        - file:${recording.path}

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

redis:
  database: mall
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24hour

secure:
  ignored:
    urls: # url with no authentication
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /user/check_user/**
      - /user/login
      - /user/register
      - /user/register_vxml
      - /user/logout
      - /pms/**
      - /hello
      - /static/**