### Get All Orders
GET {{host}}/pms/orderMaster/list

### Create one New Order
POST {{host}}/pms/orderMaster/create
Content-Type: application/json

{
  "userId": 2,

  "orderStatus": 0
}

### Get One Order By Id
GET {{host}}/pms/orderMaster/get/2

### Get Orders By User Id
GET {{host}}/pms/orderMaster/getByUserId/2

### Delete One Order By Id
DELETE {{host}}/pms/orderMaster/delete/2


