### Create one orderDetail for an Order
POST {{host}}/pms/orderDetail/create
Content-Type: application/json

{
  "orderId": 2,
  "productId": 12,
  "productPrice": 810.00,
  "productQuantity": 2,
  "productTotalPrice": 1620.00
}
