### Get All Products
GET https://ict4d-group16.herokuapp.com/pms/orderMaster/list

### Create one New Product
POST https://ict4d-group16.herokuapp.com/pms/orderMaster/create
Content-Type: application/json

{
  "userId": 2,
  "orderStatus": 0
}

### Get One Product By Id
GET https://ict4d-group16.herokuapp.com/pms/orderMaster/get/1

### Delete One Product By Id
DELETE https://ict4d-group16.herokuapp.com/pms/orderMaster/delete/1


