### Get All Products
GET https://ict4d-group16.herokuapp.com/pms/product/list

### Create one New Product
POST https://ict4d-group16.herokuapp.com/pms/product/create
Content-Type: application/json

{
  "productName": "toy_23",
  "phone": "114514",
  "price": 1.00,
  "quantity": 1,
  "description": "For fun",
  "recordingId": 13
}

### Get One Product By Product Id
POST https://ict4d-group16.herokuapp.com/pms/product/get
content-type: application/json

{
  "productId": 8
}

### Get Products By Recording Id
POST https://ict4d-group16.herokuapp.com/pms/product/get
Content-Type: application/json

{
  "recordingId": 13
}

### Delete One Product By Id
DELETE https://ict4d-group16.herokuapp.com/pms/product/delete/1

