### Get All Products
GET {{host}}/pms/product/list

### Create one New Product
POST {{host}}/pms/product/create
Content-Type: application/json

{
  "productName": "toy_23",
  "phone": "114514",
  "price": 1.00,
  "quantity": 1,
  "description": "For fun",
  "recordingId": 13
}

### Get One Product By Product Id
POST {{host}}/pms/product/search
content-type: application/json

{
  "productId": 8
}

### Get Products By Recording Id
POST {{host}}/pms/product/search
Content-Type: application/json

{
  "recordingId": 13
}

### Delete One Product By Id
DELETE {{host}}/pms/product/delete/1

