### Get a list of all recordings
GET {{host}}/pms/recording/list
Accept: application/json

### Send a form with the phone number and recording
POST {{host}}/pms/recording/create
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="phone"

114514
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="sample.wav"
Content-Type: audio/wav

< ./file_example_WAV_1MG.wav
--WebAppBoundary--