### Create a name translate text for a product
POST {{host}}/pms/translate/createName
content-type: application/json

{
    "productId": 8,
    "text": "This is a translated text",
    "language": "English"
}

### Create a description translate text for a product
POST {{host}}/pms/translate/createDescription
content-type: application/json

{
  "productId": 8,
  "text": "This is a translated text",
  "language": "English"
}